# docker/docker-compose.yml
version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: agenteia_postgres
    environment:
      POSTGRES_USER: agenteia_user
      POSTGRES_PASSWORD: agenteia_password_2025
      POSTGRES_DB: agenteia_db
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agenteia_user -d agenteia_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: [
      "postgres",
      "-c", "max_connections=200",
      "-c", "shared_preload_libraries=vector",
      "-c", "log_statement=all",
      "-c", "log_destination=stderr"
    ]

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: agenteia_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@agenteia.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  default:
    name: agenteia_network
